Circleci now supplies go1.7, which breaks things. (#958)
Compiling with go1.7 causes our vendored dependencies to fail to build:

vendor/golang.org/x/net/context/context.go:141: undefined: background
vendor/golang.org/x/net/context/context.go:150: undefined: todo

This change adds the ubuntu-specific go 1.6 path to $PATH for circleci,
and checks to make sure the go version is 1.6 (and disallows 1.7 which
was previously accepted).