Removing top-level __init__.py
It makes the name of the directory containing the source-code
significant. If the dir is called 'scion', tests work. If it's called,
e.g. 'scion.git', then this happens:

E
======================================================================
ERROR: Failure: ImportError (No module named 'scion')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/scion/.local/lib/python3.4/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/scion/.local/lib/python3.4/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/scion/.local/lib/python3.4/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/scion/.local/lib/python3.4/site-packages/nose/importer.py", line 79, in importFromDir
    fh, filename, desc = find_module(part, path)
  File "/usr/lib/python3.4/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'scion'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)