deps: add libssl-dev dependency
Otherwise the `openssl/md5.h` header can be missing in some systems.
E.g. by running `scion start` with a locally generated topology (with docker):
```
...
bbcp_MD5_openssl.h:47:10: fatal error: openssl/md5.h: No such file or directory
 #include "openssl/md5.h"
          ^~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [../obj/amd64_linux/bbcp_ChkSum.o] Error 1
make[2]: *** [makeLinuxx86_64] Error 2
make[1]: *** [Linux] Error 2
make: *** [all] Error 2
...
```
Closes #4194
GitOrigin-RevId: 083f8174e73da8f67e05561b08ba199c38d8a4d4